{% set version = "0.2.1" %}

package:
  name: thermohubclient
  version: {{ version }}

source:
  url: https://github.com/thermohub/thermohubclient/archive/v{{ version }}.tar.gz
  sha256: 4afcc592025a130e5b92342f6b6eac959237a9e337e888304ece9cb3e4530b52

build:
  number: 4
  skip: true  # [win and vc<14]

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ stdlib("c") }}
    - cmake
    - ninja  # [win]
    - make  # [unix]
  host:
    - pybind11
    - nlohmann_json
    - numpy
    - python
    - jsonarango
    - velocypack
    - libcurl
  run:
    - python
test:
  imports:
    - thermohubclient
  commands:
    - test -d ${PREFIX}/include/ThermoHubClient  # [unix]
    - test -f ${PREFIX}/include/ThermoHubClient/ThermoHubClient.h  # [unix]
    - if exist %LIBRARY_PREFIX%\include\ThermoHubClient\ThermoHubClient.h (exit 0) else (exit 1)  # [win]

about:
  home: https://github.com/thermohub/thermohubclient
  license: LGPL-3.0
  license_family: LGPL
  license_file: LICENSE
  summary: A client for retrieving data from ThermoHub thermodynamic database.
  doc_url: https://github.com/thermohub/thermohubclient
  dev_url: https://github.com/thermohub/thermohubclient

extra:
  recipe-maintainers:
    - gdmiron
